function displayGUI ()

if guiGetVisible( Main_Window ) == true then 
guiSetVisible ( Main_Window, false )
showCursor ( false )
ishidden = true
else if ishidden == true then
guiSetVisible ( Main_Window, true )
showCursor ( true )
else

--Main_Window = guiCreateWindow(231,16,725,924,"Spawn A Vehicle",false)
Main_Window = guiCreateWindow(0.2,0.02,0.6,0.9,"Spawn A Vehicle",true)
showCursor ( true )
--list_vehicles = guiCreateGridList(62,48,288,841,false,Main_Window)
list_vehicles = guiCreateGridList(0.0807,0.0519,0.3503,0.9004,true,Main_Window)
guiGridListSetSelectionMode(list_vehicles,2)
vehicle_column = guiGridListAddColumn ( list_vehicles, "Vehicles", 0.85 )
list_vehicles2 = guiCreateGridList(0.0807,0.0519,0.3503,0.9004,true,Main_Window)
guiGridListSetSelectionMode(list_vehicles2,2)
vehicle_column = guiGridListAddColumn ( list_vehicles2, "Vehicles", 0.85 )
guiSetVisible ( list_vehicles2, false )
-- 2-Door and Compact cars
cat1 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat1, vehicle_column, "2-Door and Compact cars", true, false )
Alpha = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Alpha, vehicle_column, "Alpha", false, false )
Hustler = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Hustler, vehicle_column, "Hustler", false, false )
BlistaCompact = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, BlistaCompact, vehicle_column, "Blista Compact", false, false )
Majestic = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Majestic, vehicle_column, "Majestic", false, false )
Bravura = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Bravura, vehicle_column, "Bravura", false, false )
Manana = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Manana, vehicle_column, "Manana", false, false )
Buccaneer = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Buccaneer, vehicle_column, "Buccaneer", false, false )
Picador = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Picador, vehicle_column, "Picador", false, false )
Cadrona = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Cadrona, vehicle_column, "Cadrona", false, false )
Previon = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Previon, vehicle_column, "Previon", false, false )
Club = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Club, vehicle_column, "Club", false, false )
Stafford = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Stafford, vehicle_column, "Stafford", false, false )
Esperanto = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Esperanto, vehicle_column, "Esperanto", false, false )
Stallion = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Stallion, vehicle_column, "Stallion", false, false )
Feltzer = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Felzter, vehicle_column, "Feltzer", false, false )
Tampa = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Tampa, vehicle_column, "Tampa", false, false )
Fortune = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Fortune, vehicle_column, "Fortune", false, false )
Virgo = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Virgo, vehicle_column, "Virgo", false, false )
Hermes = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Hermes, vehicle_column, "Hermes", false, false )
cat2 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat2, vehicle_column, "4-Door and Luxury cars", true, false )
Admiral = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Admiral, vehicle_column, "Admiral", false, false )
Oceanic = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Oceanic, vehicle_column, "Oceanic", false, false )
DamagedGlendale = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, DamagedGlendale, vehicle_column, "Damaged Glendale", false )
Premier = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Premier, vehicle_column, "Premier", false, false )
Elegant = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Elegant, vehicle_column, "Elegant", false, false )
Primo = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Primo, vehicle_column, "Primo", false, false )
Emperor = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Emperor, vehicle_column, "Emperor", false, false )
Sentinel = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Sentinel, vehicle_column, "Sentinel", false, false )
Euros = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Euros, vehicle_column, "Euros", false, false )
Stretch = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Stretch, vehicle_column, "Stretch", false, false )
Glendale = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Glendale, vehicle_column, "Glendale", false, false )
Sunrise = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Sunrise, vehicle_column, "Sunrise", false, false )
Greenwood = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Greenwood, vehicle_column, "Greenwood", false, false )
Tahoma = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Tahoma, vehicle_column, "Tahoma", false, false )
Intruder = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Intruder, vehicle_column, "Intruder", false, false )
Vincent = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Vincent, vehicle_column, "Vincent", false, false )
Merit = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Merit, vehicle_column, "Merit", false, false )
Washington = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Washington, vehicle_column, "Washington", false, false )
Nebula = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Nebula, vehicle_column, "Nebula", false, false )
Willard = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Willard, vehicle_column, "Willard", false, false )
cat3 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat3, vehicle_column, "Aircraft", true, false )
Andromada = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Andromada, vehicle_column, "Andromada", false, false )
Nevada = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Nevada, vehicle_column, "Nevada", false, false )
AT400 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, AT400, vehicle_column, "AT-400", false, false )
NewsChopper = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, NewsChopper, vehicle_column, "News Chopper", false, false )
Beagle = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Beagle, vehicle_column, "Beagle", false, false )
polMav = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, polMav, vehicle_column, "Police Maverick", false, false )
Cargobob = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Cargobob, vehicle_column, "Cargobob", false, false )
Raindance = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Raindance, vehicle_column, "Raindance", false, false )
Cropduster = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Cropduster, vehicle_column, "Cropduster", false, false )
Rustler = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Rustler, vehicle_column, "Rustler", false, false )
Dodo = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Dodo, vehicle_column, "Dodo", false, false )
Seasparrow = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Seasparrow, vehicle_column, "Seasparrow", false, false )
Hunter = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Hunter, vehicle_column, "Hunter", false, false )
Shamal = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Shamal, vehicle_column, "Shamal", false, false )
Hydra = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Hydra, vehicle_column, "Hydra", false, false )
Skimmer = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Skimmer, vehicle_column, "Skimmer", false, false )
Leviathan = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Leviathan, vehicle_column, "Leviathan", false, false )
Sparrow = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Sparrow, vehicle_column, "Sparrow", false, false )
Maverick = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Maverick, vehicle_column, "Maverick", false, false )
stunt = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, stunt, vehicle_column, "Stuntplane", false, false )
cat4 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat4, vehicle_column, "Bikes", true, false )
bf400 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, bf400, vehicle_column, "BF-400", false, false )
Bike = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Bike, vehicle_column, "Bike", false, false )
bmx = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, bmx, vehicle_column, "BMX", false, false )
Faggio = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Faggio, vehicle_column, "Faggio", false, false )
FCR900 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, FCR900, vehicle_column, "FCR-900", false, false )
Freeway = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Freeway, vehicle_column, "Freeway", false, false )
mb = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, mb, vehicle_column, "Mountain Bike", false, false )
NRG500 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, NRG500, vehicle_column, "NRG-500", false, false )
PCJ600 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, PCJ600, vehicle_column, "PCJ-600", false, false )
Pizzaboy = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Pizzaboy, vehicle_column, "Pizza Boy", false, false )
Sanchez = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Sanchez, vehicle_column, "Sanchez", false, false )
Wayfarer = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Wayfarer, vehicle_column, "Wayfarer", false, false )
cat5 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat5, vehicle_column, "Boats", true, false )
coastguard = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, coastguard, vehicle_column, "Coastguard", false, false )
Dinghy = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Dinghy, vehicle_column, "Dinghy", false, false )
Jetmax = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Jetmax, vehicle_column, "Jetmax", false, false )
Launch = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Launch, vehicle_column, "Launch", false, false )
Marquis = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Marquis, vehicle_column, "Marquis", false, false )
Predator = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Predator, vehicle_column, "Predator", false, false )
Reefer = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Reefer, vehicle_column, "Reefer", false, false )
Speeder = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Speeder, vehicle_column, "Speeder", false, false )
Squalo = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Squalo, vehicle_column, "Squalo", false, false )
Tropic = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Tropic, vehicle_column, "Tropic", false, false )
cat6 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat6, vehicle_column, "Civil Servant / Public Transportation", true, false )
Baggage = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Baggage, vehicle_column, "Baggage", false, false )
Utilityvan = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Utilityvan, vehicle_column, "Utility Van", false, false )
Bus = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Bus, vehicle_column, "Bus", false, false )
Cabbie = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Cabbie, vehicle_column, "Cabbie", false, false )
Coach = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Coach, vehicle_column, "Coach", false, false )
Sweeper = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Sweeper, vehicle_column, "Sweeper", false, false )
Taxi = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Taxi, vehicle_column, "Taxi", false, false )
Towtruck = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Towtruck, vehicle_column, "Towtruck", false, false )
Trashmaster = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Trashmaster, vehicle_column, "Trashmaster", false, false )
cat7 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat7, vehicle_column, "Government Vehicles", true, false )
Ambulance = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Ambulance, vehicle_column, "Ambulance", false, false )
Barracks = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Barracks, vehicle_column, "Barracks", false, false )
Enforcer = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Enforcer, vehicle_column, "Enforcer", false, false )
FBIrancher = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, FBIrancher, vehicle_column, "FBI Rancher", false, false )
fbitruck = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, fbitruck, vehicle_column, "FBI Truck", false, false )
Firetruck = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Firetruck, vehicle_column, "Fire Truck", false, false )
Firetruckl = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Firetruckl, vehicle_column, "Fire Truck (ladder)", false, false )
hpv100 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, hpv100, vehicle_column, "HPV1000", false, false )
Patriot = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Patriot, vehicle_column, "Patriot", false, false )
PoliceLV = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, PoliceLV, vehicle_column, "Police LV", false, false )
policesf = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, policesf, vehicle_column, "Police SF", false, false )
policels = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, policels, vehicle_column, "Police LS", false, false )
policeranger = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, policeranger, vehicle_column, "Police Ranger", false, false )
Rhino = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Rhino, vehicle_column, "Rhino", false, false )
Swat = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Swat, vehicle_column, "S.W.A.T.", false, false )
securicar = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, securicar, vehicle_column, "Securicar", false, false )
cat8 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat8, vehicle_column, "Heavy and Utility trucks", true, false )
Benson = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Benson, vehicle_column, "Benson", false, false )
blackbox = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, blackbox, vehicle_column, "Black Boxville", false, false )
box = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, box, vehicle_column, "Boxville", false, false )
cemtruck = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cemtruck, vehicle_column, "Cement Truck", false, false )
comharv = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, comharv, vehicle_column, "Combine Harvester", false, false )
DFT30 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, DFT30, vehicle_column, "DFT-30", false, false )
Dozer = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Dozer, vehicle_column, "Dozer", false, false )
Dumper = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Dumper, vehicle_column, "Dumper", false, false )
Dune = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Dune, vehicle_column, "Dune", false, false )
Flatbed = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Flatbed, vehicle_column, "Flatbed", false, false )
hotdog = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, hotdog, vehicle_column, "Hotdog", false, false )
Linerunner = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Linerunner, vehicle_column, "Linerunner", false, false )
linerunner2 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, linerunner2, vehicle_column, "Linerunner 2", false, false )
Mrwhop = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Mrwhop, vehicle_column, "Mr.Whoopee", false, false )
Mule = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Mule, vehicle_column, "Mule", false, false )
Packer = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Packer, vehicle_column, "Packer", false, false )
Roadtrain = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Roadtrain, vehicle_column, "Roadtrain", false, false )
Tractor = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Tractor, vehicle_column, "Tractor", false, false )
Yankee = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Yankee, vehicle_column, "Yankee", false, false )
cat9 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat9, vehicle_column, "Light Trucks and Vans", true, false )
berkrc = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, berkrc, vehicle_column, "Berkley's RC Van", false, false )
Bobcat = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Bobcat, vehicle_column, "Bobcat", false, false )
Burrito = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Burrito, vehicle_column, "Burrito", false, false )
Dmgsad = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Dmgsad, vehicle_column, "Damaged Sadler", false, false )
Forklift = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Forklift, vehicle_column, "Forklift", false, false )
Moonbeam = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Moonbeam, vehicle_column, "Moonbeam", false, false )
Mower = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Mower, vehicle_column, "Mower", false, false )
NewsVan = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, NewsVan, vehicle_column, "News Van", false, false )
Pony = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Pony, vehicle_column, "Pony", false, false )
Rumpo = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Rumpo, vehicle_column, "Rumpo", false, false )
Sadler = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Sadler, vehicle_column, "Sadler", false, false )
Tug = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Tug, vehicle_column, "Tug", false, false )
Walton = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Walton, vehicle_column, "Walton", false, false )
Yosemite = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Yosemite, vehicle_column, "Yosemite", false, false )
cat10 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat10, vehicle_column, "Lowriders", true, false )
-- low riders \|/  vans |^|^|
Blade = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Blade, vehicle_column, "Blade", false, false )
Broadway = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Broadway, vehicle_column, "Broadway", false, false )
Remington = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Remington, vehicle_column, "Remington", false, false )
Savanna = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Savanna, vehicle_column, "Savanna", false, false )
Slamvan = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Slamvan, vehicle_column, "Slamvan", false, false )
Tornado = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Tornado, vehicle_column, "Tornado", false, false )
Voodoo = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Voodoo, vehicle_column, "Voodoo", false, false )
cat11 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat11, vehicle_column, "Muscle Cars", true, false )
-- muscle cars
Buffalo = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Buffalo, vehicle_column, "Buffalo", false, false )
Clover = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Clover, vehicle_column, "Clover", false, false )
Phoenix = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Phoenix, vehicle_column, "Phoenix", false, false )
Sabre = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Sabre, vehicle_column, "Sabre", false, false )
--trains
cat12 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat12, vehicle_column, "Trains and Railroad Cars", true, false )
Train = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Train, vehicle_column, "Train", false, false )
Freight = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Freight, vehicle_column, "Freight", false, false )
BrownStreak = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, BrownStreak, vehicle_column, "Brown Streak", false, false )
Brownstreakcar = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Brownstreakcar, vehicle_column, "Brown Streak Carriage", false, false )
Flatfreight = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Flatfreight, vehicle_column, "Flat Freight", false, false )
boxfreight= guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, boxfreight, vehicle_column, "Box Freight", false, false )
-- RC
cat13 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat13, vehicle_column, "RC Vehicles", true, false )
RCbandit = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, RCbandit, vehicle_column, "RC Bandit", false, false )
RCbaron = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, RCbaron, vehicle_column, "RC Baron", false, false )
RCgoblin= guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, RCgoblin, vehicle_column, "RC Goblin", false, false )
RCraider = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, RCraider, vehicle_column, "RC Raider", false, false )
RCtiger = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, RCtiger, vehicle_column, "RC Tiger", false, false )
RCcam = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, RCcam, vehicle_column, "RC Cam", false, false )
-- recreational
cat14 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat14, vehicle_column, "Recreational", true, false )
bandito = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, bandito, vehicle_column, "Bandito", false, false )
bfinject = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, bfinject, vehicle_column, "BF Injection", false, false )
bloodbanger = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, bloodbanger, vehicle_column, "Bloodring Banger", false, false )
caddy = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, caddy, vehicle_column, "Caddy", false, false )
Camper = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Camper, vehicle_column, "Camper", false, false )
Journey = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Journey, vehicle_column, "Journey", false, false )
Kart = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Kart, vehicle_column, "Kart", false, false )
Mesa = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Mesa, vehicle_column, "Mesa", false, false )
Monster = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Monster, vehicle_column, "Monster", false, false )
Monster2 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Monster2, vehicle_column, "Monster 2", false, false )
Monster3 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Monster3, vehicle_column, "Monster 3", false, false )
--------------------------
quad = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, quad, vehicle_column, "Quadbike", false, false )
sandking = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, sandking, vehicle_column, "Sandking", false, false )
vortex = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, vortex, vehicle_column, "Vortex", false, false )
-- street racers
cat15 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat15, vehicle_column, "Street Racers", true, false )
banshee = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, banshee, vehicle_column, "Banshee", false, false )
bullet = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, bullet, vehicle_column, "Bullet", false, false )
Cheetah = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Cheetah, vehicle_column, "Cheetah", false, false )
Comet = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Comet, vehicle_column, "Comet", false, false )
Elegy = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Elegy, vehicle_column, "Elegy", false, false )
Flash = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Flash, vehicle_column, "Flash", false, false )
Hotknife = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Hotknife, vehicle_column, "Hotknife", false, false )
hotring = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, hotring, vehicle_column, "Hotring Racer", false, false )
hotring2 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, hotring2, vehicle_column, "Hotring Racer 2", false, false )
hoting3 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, hotring3, vehicle_column, "Hotring Racer 3", false, false )
infernus = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, infernus, vehicle_column, "Infernus", false, false )
jester = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, jester, vehicle_column, "Jester", false, false )
Stratum = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Stratum, vehicle_column, "Stratum", false, false )
Sultan = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Sultan, vehicle_column, "Sultan", false, false )
supergt = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, supergt, vehicle_column, "Super GT", false, false )
turismo = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, turismo, vehicle_column, "Turismo", false, false )
Uranus = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Uranus, vehicle_column, "Uranus", false, false )
Windsor = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Windsor, vehicle_column, "Windsor", false, false )
ZR350 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, ZR350, vehicle_column, "ZR-350", false, false )
-- suv's
cat16 = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, cat16, vehicle_column, "SUVs and Wagons", true, false )
Huntley = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Huntley, vehicle_column, "Huntley", false, false )
land = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, land, vehicle_column, "Landstalker", false, false )
peer = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, peer, vehicle_column, "Perennial", false, false )
Rancher = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Rancher, vehicle_column, "Rancher", false, false )
Regina = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Regina, vehicle_column, "Regina", false, false )
Romero = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Romero, vehicle_column, "Romero", false, false )
Solair = guiGridListAddRow ( list_vehicles2 )
guiGridListSetItemText ( list_vehicles2, Solair, vehicle_column, "Solair", false, false )
Admiral = guiGridListAddRow ( list_vehicles )
Alpha = guiGridListAddRow ( list_vehicles )
Ambulance = guiGridListAddRow ( list_vehicles )
Andromada = guiGridListAddRow ( list_vehicles )
AT400 = guiGridListAddRow ( list_vehicles )
Baggage = guiGridListAddRow ( list_vehicles )
bandito = guiGridListAddRow ( list_vehicles )
banshee = guiGridListAddRow ( list_vehicles )
Barracks = guiGridListAddRow ( list_vehicles )
Beagle = guiGridListAddRow ( list_vehicles )
Benson = guiGridListAddRow ( list_vehicles )
berkrc = guiGridListAddRow ( list_vehicles )
bf400 = guiGridListAddRow ( list_vehicles )
bfinject = guiGridListAddRow ( list_vehicles )
Bike = guiGridListAddRow ( list_vehicles )
Blade = guiGridListAddRow ( list_vehicles )
BlistaCompact = guiGridListAddRow ( list_vehicles )
bloodbanger = guiGridListAddRow ( list_vehicles )
bmx = guiGridListAddRow ( list_vehicles )
Bobcat = guiGridListAddRow ( list_vehicles )
box = guiGridListAddRow ( list_vehicles )
boxfreight= guiGridListAddRow ( list_vehicles )
Bravura = guiGridListAddRow ( list_vehicles )
Broadway = guiGridListAddRow ( list_vehicles )
BrownStreak = guiGridListAddRow ( list_vehicles )
Brownstreakcar = guiGridListAddRow ( list_vehicles )
Buccaneer = guiGridListAddRow ( list_vehicles )
Buffalo = guiGridListAddRow ( list_vehicles )
bullet = guiGridListAddRow ( list_vehicles )
Burrito = guiGridListAddRow ( list_vehicles )
Bus = guiGridListAddRow ( list_vehicles )
Cabbie = guiGridListAddRow ( list_vehicles )
caddy = guiGridListAddRow ( list_vehicles )
Cadrona = guiGridListAddRow ( list_vehicles )
Camper = guiGridListAddRow ( list_vehicles )
Cargobob = guiGridListAddRow ( list_vehicles )
cemtruck = guiGridListAddRow ( list_vehicles )
Cheetah = guiGridListAddRow ( list_vehicles )
Clover = guiGridListAddRow ( list_vehicles )
Club = guiGridListAddRow ( list_vehicles )
Coach = guiGridListAddRow ( list_vehicles )
coastguard = guiGridListAddRow ( list_vehicles )
Comet = guiGridListAddRow ( list_vehicles )
comharv = guiGridListAddRow ( list_vehicles )
Cropduster = guiGridListAddRow ( list_vehicles )
DamagedGlendale = guiGridListAddRow ( list_vehicles )
DFT30 = guiGridListAddRow ( list_vehicles )
Dinghy = guiGridListAddRow ( list_vehicles )
Dmgsad = guiGridListAddRow ( list_vehicles )
Dodo = guiGridListAddRow ( list_vehicles )
Dozer = guiGridListAddRow ( list_vehicles )
Dumper = guiGridListAddRow ( list_vehicles )
Dune = guiGridListAddRow ( list_vehicles )
Elegant = guiGridListAddRow ( list_vehicles )
Elegy = guiGridListAddRow ( list_vehicles )
Emperor = guiGridListAddRow ( list_vehicles )
Enforcer = guiGridListAddRow ( list_vehicles )
Esperanto = guiGridListAddRow ( list_vehicles )
Euros = guiGridListAddRow ( list_vehicles )
Faggio = guiGridListAddRow ( list_vehicles )
FBIrancher = guiGridListAddRow ( list_vehicles )
fbitruck = guiGridListAddRow ( list_vehicles )
FCR900 = guiGridListAddRow ( list_vehicles )
Feltzer = guiGridListAddRow ( list_vehicles )
Firetruck = guiGridListAddRow ( list_vehicles )
Firetruckl = guiGridListAddRow ( list_vehicles )
Flash = guiGridListAddRow ( list_vehicles )
Flatbed = guiGridListAddRow ( list_vehicles )
Flatfreight = guiGridListAddRow ( list_vehicles )
Flatfreight = guiGridListAddRow ( list_vehicles )
Forklift = guiGridListAddRow ( list_vehicles )
Fortune = guiGridListAddRow ( list_vehicles )
Freeway = guiGridListAddRow ( list_vehicles )
Freight = guiGridListAddRow ( list_vehicles )
Glendale = guiGridListAddRow ( list_vehicles )
Greenwood = guiGridListAddRow ( list_vehicles )
Hermes = guiGridListAddRow ( list_vehicles )
hotdog = guiGridListAddRow ( list_vehicles )
Hotknife = guiGridListAddRow ( list_vehicles )
hotring = guiGridListAddRow ( list_vehicles )
hotring2 = guiGridListAddRow ( list_vehicles )
hotring3 = guiGridListAddRow ( list_vehicles )
hpv100 = guiGridListAddRow ( list_vehicles )
hunter = guiGridListAddRow ( list_vehicles )
Huntley = guiGridListAddRow ( list_vehicles )
Hustler = guiGridListAddRow ( list_vehicles )
hydra = guiGridListAddRow ( list_vehicles )
infernus = guiGridListAddRow ( list_vehicles )
Intruder = guiGridListAddRow ( list_vehicles )
jester = guiGridListAddRow ( list_vehicles )
Jetmax = guiGridListAddRow ( list_vehicles )
Journey = guiGridListAddRow ( list_vehicles )
Kart = guiGridListAddRow ( list_vehicles )
land = guiGridListAddRow ( list_vehicles )
Launch = guiGridListAddRow ( list_vehicles )
Leviathan = guiGridListAddRow ( list_vehicles )
Linerunner = guiGridListAddRow ( list_vehicles )
Majestic = guiGridListAddRow ( list_vehicles )
Manana = guiGridListAddRow ( list_vehicles )
Marquis = guiGridListAddRow ( list_vehicles )
Maverick = guiGridListAddRow ( list_vehicles )
mb = guiGridListAddRow ( list_vehicles )
Merit = guiGridListAddRow ( list_vehicles )
Mesa = guiGridListAddRow ( list_vehicles )
Monster = guiGridListAddRow ( list_vehicles )
Monster2 = guiGridListAddRow ( list_vehicles )
Monster3 = guiGridListAddRow ( list_vehicles )
Moonbeam = guiGridListAddRow ( list_vehicles )
Mower = guiGridListAddRow ( list_vehicles )
Mrwhop = guiGridListAddRow ( list_vehicles )
Mule = guiGridListAddRow ( list_vehicles )
Nebula = guiGridListAddRow ( list_vehicles )
Nevada = guiGridListAddRow ( list_vehicles )
NewsChopper = guiGridListAddRow ( list_vehicles )
NewsVan = guiGridListAddRow ( list_vehicles )
NRG500 = guiGridListAddRow ( list_vehicles )
Oceanic = guiGridListAddRow ( list_vehicles )
Packer = guiGridListAddRow ( list_vehicles )
Patriot = guiGridListAddRow ( list_vehicles )
PCJ600 = guiGridListAddRow ( list_vehicles )
peer = guiGridListAddRow ( list_vehicles )
Phoenix = guiGridListAddRow ( list_vehicles )
Picador = guiGridListAddRow ( list_vehicles )
Pizzaboy = guiGridListAddRow ( list_vehicles )
policels = guiGridListAddRow ( list_vehicles )
PoliceLV = guiGridListAddRow ( list_vehicles )
policeranger = guiGridListAddRow ( list_vehicles )
policesf = guiGridListAddRow ( list_vehicles )
polMav = guiGridListAddRow ( list_vehicles )
Pony = guiGridListAddRow ( list_vehicles )
Predator = guiGridListAddRow ( list_vehicles )
Premier = guiGridListAddRow ( list_vehicles )
Previon = guiGridListAddRow ( list_vehicles )
Primo = guiGridListAddRow ( list_vehicles )
quad = guiGridListAddRow ( list_vehicles )
Raindance = guiGridListAddRow ( list_vehicles )
Rancher = guiGridListAddRow ( list_vehicles )
RCbandit = guiGridListAddRow ( list_vehicles )
RCbaron = guiGridListAddRow ( list_vehicles )
RCgoblin= guiGridListAddRow ( list_vehicles )
RCraider = guiGridListAddRow ( list_vehicles )
RCtiger = guiGridListAddRow ( list_vehicles )
Reefer = guiGridListAddRow ( list_vehicles )
Regina = guiGridListAddRow ( list_vehicles )
Remington = guiGridListAddRow ( list_vehicles )
rhino = guiGridListAddRow ( list_vehicles )
Roadtrain = guiGridListAddRow ( list_vehicles )
Romero = guiGridListAddRow ( list_vehicles )
Rumpo = guiGridListAddRow ( list_vehicles )
Rustler = guiGridListAddRow ( list_vehicles )
Sabre = guiGridListAddRow ( list_vehicles )
Sadler = guiGridListAddRow ( list_vehicles )
Sanchez = guiGridListAddRow ( list_vehicles )
sandking = guiGridListAddRow ( list_vehicles )
Savanna = guiGridListAddRow ( list_vehicles )
Seasparrow = guiGridListAddRow ( list_vehicles )
securicar = guiGridListAddRow ( list_vehicles )
Sentinel = guiGridListAddRow ( list_vehicles )
Shamal = guiGridListAddRow ( list_vehicles )
Skimmer = guiGridListAddRow ( list_vehicles )
Slamvan = guiGridListAddRow ( list_vehicles )
Solair = guiGridListAddRow ( list_vehicles )
Sparrow = guiGridListAddRow ( list_vehicles )
Speeder = guiGridListAddRow ( list_vehicles )
Squalo = guiGridListAddRow ( list_vehicles )
Stafford = guiGridListAddRow ( list_vehicles )
Stallion = guiGridListAddRow ( list_vehicles )
Stratum = guiGridListAddRow ( list_vehicles )
Stretch = guiGridListAddRow ( list_vehicles )
stunt = guiGridListAddRow ( list_vehicles )
Sultan = guiGridListAddRow ( list_vehicles )
Sunrise = guiGridListAddRow ( list_vehicles )
supergt = guiGridListAddRow ( list_vehicles )
Swat = guiGridListAddRow ( list_vehicles )
Sweeper = guiGridListAddRow ( list_vehicles )
Tahoma = guiGridListAddRow ( list_vehicles )
Tampa = guiGridListAddRow ( list_vehicles )
Taxi = guiGridListAddRow ( list_vehicles )
Tornado = guiGridListAddRow ( list_vehicles )
Towtruck = guiGridListAddRow ( list_vehicles )
Tractor = guiGridListAddRow ( list_vehicles )
Train = guiGridListAddRow ( list_vehicles )
Trashmaster = guiGridListAddRow ( list_vehicles )
Tropic = guiGridListAddRow ( list_vehicles )
Tug = guiGridListAddRow ( list_vehicles )
turismo = guiGridListAddRow ( list_vehicles )
Uranus = guiGridListAddRow ( list_vehicles )
Utilityvan = guiGridListAddRow ( list_vehicles )
Vincent = guiGridListAddRow ( list_vehicles )
Virgo = guiGridListAddRow ( list_vehicles )
Voodoo = guiGridListAddRow ( list_vehicles )
vortex = guiGridListAddRow ( list_vehicles )
Walton = guiGridListAddRow ( list_vehicles )
Washington = guiGridListAddRow ( list_vehicles )
Wayfarer = guiGridListAddRow ( list_vehicles )
Willard = guiGridListAddRow ( list_vehicles )
Windsor = guiGridListAddRow ( list_vehicles )
Yankee = guiGridListAddRow ( list_vehicles )
Yosemite = guiGridListAddRow ( list_vehicles )
ZR350 = guiGridListAddRow ( list_vehicles )
guiGridListSetItemText ( list_vehicles, Admiral, vehicle_column, "Admiral", false, false )
guiGridListSetItemText ( list_vehicles, Alpha, vehicle_column, "Alpha", false, false )
guiGridListSetItemText ( list_vehicles, Ambulance, vehicle_column, "Ambulance", false, false )
guiGridListSetItemText ( list_vehicles, Andromada, vehicle_column, "Andromada", false, false )
guiGridListSetItemText ( list_vehicles, AT400, vehicle_column, "AT-400", false, false )
guiGridListSetItemText ( list_vehicles, Baggage, vehicle_column, "Baggage", false, false )
guiGridListSetItemText ( list_vehicles, bandito, vehicle_column, "Bandito", false, false )
guiGridListSetItemText ( list_vehicles, banshee, vehicle_column, "Banshee", false, false )
guiGridListSetItemText ( list_vehicles, Barracks, vehicle_column, "Barracks", false, false )
guiGridListSetItemText ( list_vehicles, Beagle, vehicle_column, "Beagle", false, false )
guiGridListSetItemText ( list_vehicles, Benson, vehicle_column, "Benson", false, false )
guiGridListSetItemText ( list_vehicles, berkrc, vehicle_column, "Berkley's RC Van", false, false )
guiGridListSetItemText ( list_vehicles, bf400, vehicle_column, "BF-400", false, false )
guiGridListSetItemText ( list_vehicles, bfinject, vehicle_column, "BF Injection", false, false )
guiGridListSetItemText ( list_vehicles, Bike, vehicle_column, "Bike", false, false )
guiGridListSetItemText ( list_vehicles, Blade, vehicle_column, "Blade", false, false )
guiGridListSetItemText ( list_vehicles, BlistaCompact, vehicle_column, "Blista Compact", false, false )
guiGridListSetItemText ( list_vehicles, bloodbanger, vehicle_column, "Bloodring Banger", false, false )
guiGridListSetItemText ( list_vehicles, bmx, vehicle_column, "BMX", false, false )
guiGridListSetItemText ( list_vehicles, Bobcat, vehicle_column, "Bobcat", false, false )
guiGridListSetItemText ( list_vehicles, box, vehicle_column, "Boxville", false, false )
guiGridListSetItemText ( list_vehicles, boxfreight, vehicle_column, "Box Freight", false, false )
guiGridListSetItemText ( list_vehicles, Bravura, vehicle_column, "Bravura", false, false )
guiGridListSetItemText ( list_vehicles, Broadway, vehicle_column, "Broadway", false, false )
guiGridListSetItemText ( list_vehicles, BrownStreak, vehicle_column, "Streak", false, false )
guiGridListSetItemText ( list_vehicles, Brownstreakcar, vehicle_column, "Streak Train Trailer", false, false )
guiGridListSetItemText ( list_vehicles, Buccaneer, vehicle_column, "Buccaneer", false, false )
guiGridListSetItemText ( list_vehicles, Buffalo, vehicle_column, "Buffalo", false, false )
guiGridListSetItemText ( list_vehicles, bullet, vehicle_column, "Bullet", false, false )
guiGridListSetItemText ( list_vehicles, Burrito, vehicle_column, "Burrito", false, false )
guiGridListSetItemText ( list_vehicles, Bus, vehicle_column, "Bus", false, false )
guiGridListSetItemText ( list_vehicles, Cabbie, vehicle_column, "Cabbie", false, false )
guiGridListSetItemText ( list_vehicles, caddy, vehicle_column, "Caddy", false, false )
guiGridListSetItemText ( list_vehicles, Cadrona, vehicle_column, "Cadrona", false, false )
guiGridListSetItemText ( list_vehicles, Camper, vehicle_column, "Camper", false, false )
guiGridListSetItemText ( list_vehicles, Cargobob, vehicle_column, "Cargobob", false, false )
guiGridListSetItemText ( list_vehicles, cemtruck, vehicle_column, "Cement Truck", false, false )
guiGridListSetItemText ( list_vehicles, Cheetah, vehicle_column, "Cheetah", false, false )
guiGridListSetItemText ( list_vehicles, Clover, vehicle_column, "Clover", false, false )
guiGridListSetItemText ( list_vehicles, Club, vehicle_column, "Club", false, false )
guiGridListSetItemText ( list_vehicles, Coach, vehicle_column, "Coach", false, false )
guiGridListSetItemText ( list_vehicles, coastguard, vehicle_column, "Coastguard", false, false )
guiGridListSetItemText ( list_vehicles, Comet, vehicle_column, "Comet", false, false )
guiGridListSetItemText ( list_vehicles, comharv, vehicle_column, "Combine Harvester", false, false )
guiGridListSetItemText ( list_vehicles, Cropduster, vehicle_column, "Cropduster", false, false )
guiGridListSetItemText ( list_vehicles, DamagedGlendale, vehicle_column, "Damaged Glendale", false, false )
guiGridListSetItemText ( list_vehicles, DFT30, vehicle_column, "DFT-30", false, false )
guiGridListSetItemText ( list_vehicles, Dinghy, vehicle_column, "Dinghy", false, false )
guiGridListSetItemText ( list_vehicles, Dmgsad, vehicle_column, "Damaged Sadler", false, false )
guiGridListSetItemText ( list_vehicles, Dodo, vehicle_column, "Dodo", false, false )
guiGridListSetItemText ( list_vehicles, Dozer, vehicle_column, "Dozer", false, false )
guiGridListSetItemText ( list_vehicles, Dumper, vehicle_column, "Dumper", false, false )
guiGridListSetItemText ( list_vehicles, Dune, vehicle_column, "Dune", false, false )
guiGridListSetItemText ( list_vehicles, Elegant, vehicle_column, "Elegant", false, false )
guiGridListSetItemText ( list_vehicles, Elegy, vehicle_column, "Elegy", false, false )
guiGridListSetItemText ( list_vehicles, Emperor, vehicle_column, "Emperor", false, false )
guiGridListSetItemText ( list_vehicles, Enforcer, vehicle_column, "Enforcer", false, false )
guiGridListSetItemText ( list_vehicles, Esperanto, vehicle_column, "Esperanto", false, false )
guiGridListSetItemText ( list_vehicles, Euros, vehicle_column, "Euros", false, false )
guiGridListSetItemText ( list_vehicles, Faggio, vehicle_column, "Faggio", false, false )
guiGridListSetItemText ( list_vehicles, FBIrancher, vehicle_column, "FBI Rancher", false, false )
guiGridListSetItemText ( list_vehicles, fbitruck, vehicle_column, "FBI Truck", false, false )
guiGridListSetItemText ( list_vehicles, FCR900, vehicle_column, "FCR-900", false, false )
guiGridListSetItemText ( list_vehicles, Felzter, vehicle_column, "Feltzer", false, false )
guiGridListSetItemText ( list_vehicles, Firetruck, vehicle_column, "Fire Truck", false, false )
guiGridListSetItemText ( list_vehicles, Firetruckl, vehicle_column, "Fire Truck Ladder", false, false )
guiGridListSetItemText ( list_vehicles, Flash, vehicle_column, "Flash", false, false )
guiGridListSetItemText ( list_vehicles, Flatbed, vehicle_column, "Flatbed", false, false )
guiGridListSetItemText ( list_vehicles, Flatfreight, vehicle_column, "Freight Train Flatbed", false, false )
guiGridListSetItemText ( list_vehicles, Forklift, vehicle_column, "Forklift", false, false )
guiGridListSetItemText ( list_vehicles, Fortune, vehicle_column, "Fortune", false, false )
guiGridListSetItemText ( list_vehicles, Freeway, vehicle_column, "Freeway", false, false )
guiGridListSetItemText ( list_vehicles, Freight, vehicle_column, "Freight", false, false )
guiGridListSetItemText ( list_vehicles, Glendale, vehicle_column, "Glendale", false, false )
guiGridListSetItemText ( list_vehicles, Greenwood, vehicle_column, "Greenwood", false, false )
guiGridListSetItemText ( list_vehicles, Hermes, vehicle_column, "Hermes", false, false )
guiGridListSetItemText ( list_vehicles, hotdog, vehicle_column, "Hotdog", false, false )
guiGridListSetItemText ( list_vehicles, Hotknife, vehicle_column, "Hotknife", false, false )
guiGridListSetItemText ( list_vehicles, hotring, vehicle_column, "Hotring Racer", false, false )
guiGridListSetItemText ( list_vehicles, hotring2, vehicle_column, "Hotring Racer 2", false, false )
guiGridListSetItemText ( list_vehicles, hotring3, vehicle_column, "Hotring Racer 3", false, false )
guiGridListSetItemText ( list_vehicles, hpv100, vehicle_column, "HPV1000", false, false )
guiGridListSetItemText ( list_vehicles, hunter, vehicle_column, "Hunter", false, false )
guiGridListSetItemText ( list_vehicles, Huntley, vehicle_column, "Huntley", false, false )
guiGridListSetItemText ( list_vehicles, Hustler, vehicle_column, "Hustler", false, false )
guiGridListSetItemText ( list_vehicles, hydra, vehicle_column, "Hydra", false, false )
guiGridListSetItemText ( list_vehicles, infernus, vehicle_column, "Infernus", false, false )
guiGridListSetItemText ( list_vehicles, Intruder, vehicle_column, "Intruder", false, false )
guiGridListSetItemText ( list_vehicles, jester, vehicle_column, "Jester", false, false )
guiGridListSetItemText ( list_vehicles, Jetmax, vehicle_column, "Jetmax", false, false )
guiGridListSetItemText ( list_vehicles, Journey, vehicle_column, "Journey", false, false )
guiGridListSetItemText ( list_vehicles, Kart, vehicle_column, "Kart", false, false )
guiGridListSetItemText ( list_vehicles, land, vehicle_column, "Landstalker", false, false )
guiGridListSetItemText ( list_vehicles, Launch, vehicle_column, "Launch", false, false )
guiGridListSetItemText ( list_vehicles, Leviathan, vehicle_column, "Leviathan", false, false )
guiGridListSetItemText ( list_vehicles, Linerunner, vehicle_column, "Linerunner", false, false )
guiGridListSetItemText ( list_vehicles, Majestic, vehicle_column, "Majestic", false, false )
guiGridListSetItemText ( list_vehicles, Manana, vehicle_column, "Manana", false, false )
guiGridListSetItemText ( list_vehicles, Marquis, vehicle_column, "Marquis", false, false )
guiGridListSetItemText ( list_vehicles, Maverick, vehicle_column, "Maverick", false, false )
guiGridListSetItemText ( list_vehicles, mb, vehicle_column, "Mountain Bike", false, false )
guiGridListSetItemText ( list_vehicles, Merit, vehicle_column, "Merit", false, false )
guiGridListSetItemText ( list_vehicles, Mesa, vehicle_column, "Mesa", false, false )
guiGridListSetItemText ( list_vehicles, Monster, vehicle_column, "Monster", false, false )
guiGridListSetItemText ( list_vehicles, Monster2, vehicle_column, "Monster 2", false, false )
guiGridListSetItemText ( list_vehicles, Monster3, vehicle_column, "Monster 3", false, false )
guiGridListSetItemText ( list_vehicles, Moonbeam, vehicle_column, "Moonbeam", false, false )
guiGridListSetItemText ( list_vehicles, Mower, vehicle_column, "Mower", false, false )
guiGridListSetItemText ( list_vehicles, Mrwhop, vehicle_column, "Mr. Whoopee", false, false )
guiGridListSetItemText ( list_vehicles, Mule, vehicle_column, "Mule", false, false )
guiGridListSetItemText ( list_vehicles, Nebula, vehicle_column, "Nebula", false, false )
guiGridListSetItemText ( list_vehicles, Nevada, vehicle_column, "Nevada", false, false )
guiGridListSetItemText ( list_vehicles, NewsChopper, vehicle_column, "News Chopper", false, false )
guiGridListSetItemText ( list_vehicles, NewsVan, vehicle_column, "News Van", false, false )
guiGridListSetItemText ( list_vehicles, NRG500, vehicle_column, "NRG-500", false, false )
guiGridListSetItemText ( list_vehicles, Oceanic, vehicle_column, "Oceanic", false, false )
guiGridListSetItemText ( list_vehicles, Packer, vehicle_column, "Packer", false, false )
guiGridListSetItemText ( list_vehicles, Patriot, vehicle_column, "Patriot", false, false )
guiGridListSetItemText ( list_vehicles, PCJ600, vehicle_column, "PCJ-600", false, false )
guiGridListSetItemText ( list_vehicles, peer, vehicle_column, "Perennial", false, false )
guiGridListSetItemText ( list_vehicles, Phoenix, vehicle_column, "Phoenix", false, false )
guiGridListSetItemText ( list_vehicles, Picador, vehicle_column, "Picador", false, false )
guiGridListSetItemText ( list_vehicles, Pizzaboy, vehicle_column, "Pizza Boy", false, false )
guiGridListSetItemText ( list_vehicles, policels, vehicle_column, "Police LS", false, false )
guiGridListSetItemText ( list_vehicles, PoliceLV, vehicle_column, "Police LV", false, false )
guiGridListSetItemText ( list_vehicles, policeranger, vehicle_column, "Police Ranger", false, false )
guiGridListSetItemText ( list_vehicles, policesf, vehicle_column, "Police SF", false, false )
guiGridListSetItemText ( list_vehicles, polMav, vehicle_column, "Police Maverick", false, false )
guiGridListSetItemText ( list_vehicles, Pony, vehicle_column, "Pony", false, false )
guiGridListSetItemText ( list_vehicles, Predator, vehicle_column, "Predator", false, false )
guiGridListSetItemText ( list_vehicles, Premier, vehicle_column, "Premier", false, false )
guiGridListSetItemText ( list_vehicles, Previon, vehicle_column, "Previon", false, false )
guiGridListSetItemText ( list_vehicles, Primo, vehicle_column, "Primo", false, false )
guiGridListSetItemText ( list_vehicles, quad, vehicle_column, "Quadbike", false, false )
guiGridListSetItemText ( list_vehicles, Raindance, vehicle_column, "Raindance", false, false )
guiGridListSetItemText ( list_vehicles, Rancher, vehicle_column, "Rancher", false, false )
guiGridListSetItemText ( list_vehicles, RCbandit, vehicle_column, "RC Bandit", false, false )
guiGridListSetItemText ( list_vehicles, RCbaron, vehicle_column, "RC Baron", false, false )
guiGridListSetItemText ( list_vehicles, RCgoblin, vehicle_column, "RC Goblin", false, false )
guiGridListSetItemText ( list_vehicles, RCraider, vehicle_column, "RC Raider", false, false )
guiGridListSetItemText ( list_vehicles, RCtiger, vehicle_column, "RC Tiger", false, false )
guiGridListSetItemText ( list_vehicles, Reefer, vehicle_column, "Reefer", false, false )
guiGridListSetItemText ( list_vehicles, Regina, vehicle_column, "Regina", false, false )
guiGridListSetItemText ( list_vehicles, Remington, vehicle_column, "Remington", false, false )
guiGridListSetItemText ( list_vehicles, rhino, vehicle_column, "Rhino", false, false )
guiGridListSetItemText ( list_vehicles, Roadtrain, vehicle_column, "Roadtrain", false, false )
guiGridListSetItemText ( list_vehicles, Romero, vehicle_column, "Romero", false, false )
guiGridListSetItemText ( list_vehicles, Rumpo, vehicle_column, "Rumpo", false, false )
guiGridListSetItemText ( list_vehicles, Rustler, vehicle_column, "Rustler", false, false )
guiGridListSetItemText ( list_vehicles, Sabre, vehicle_column, "Sabre", false, false )
guiGridListSetItemText ( list_vehicles, Sadler, vehicle_column, "Sadler", false, false )
guiGridListSetItemText ( list_vehicles, Sanchez, vehicle_column, "Sanchez", false, false )
guiGridListSetItemText ( list_vehicles, sandking, vehicle_column, "Sandking", false, false )
guiGridListSetItemText ( list_vehicles, Savanna, vehicle_column, "Savanna", false, false )
guiGridListSetItemText ( list_vehicles, Seasparrow, vehicle_column, "Seasparrow", false, false )
guiGridListSetItemText ( list_vehicles, securicar, vehicle_column, "Securicar", false, false )
guiGridListSetItemText ( list_vehicles, Sentinel, vehicle_column, "Sentinel", false, false )
guiGridListSetItemText ( list_vehicles, Shamal, vehicle_column, "Shamal", false, false )
guiGridListSetItemText ( list_vehicles, Skimmer, vehicle_column, "Skimmer", false, false )
guiGridListSetItemText ( list_vehicles, Slamvan, vehicle_column, "Slamvan", false, false )
guiGridListSetItemText ( list_vehicles, Solair, vehicle_column, "Solair", false, false )
guiGridListSetItemText ( list_vehicles, Sparrow, vehicle_column, "Sparrow", false, false )
guiGridListSetItemText ( list_vehicles, Speeder, vehicle_column, "Speeder", false, false )
guiGridListSetItemText ( list_vehicles, Squalo, vehicle_column, "Squalo", false, false )
guiGridListSetItemText ( list_vehicles, Stafford, vehicle_column, "Stafford", false, false )
guiGridListSetItemText ( list_vehicles, Stallion, vehicle_column, "Stallion", false, false )
guiGridListSetItemText ( list_vehicles, Stratum, vehicle_column, "Stratum", false, false )
guiGridListSetItemText ( list_vehicles, Stretch, vehicle_column, "Stretch", false, false )
guiGridListSetItemText ( list_vehicles, stunt, vehicle_column, "Stuntplane", false, false )
guiGridListSetItemText ( list_vehicles, Sultan, vehicle_column, "Sultan", false, false )
guiGridListSetItemText ( list_vehicles, Sunrise, vehicle_column, "Sunrise", false, false )
guiGridListSetItemText ( list_vehicles, supergt, vehicle_column, "Super GT", false, false )
guiGridListSetItemText ( list_vehicles, Swat, vehicle_column, "S.W.A.T.", false, false )
guiGridListSetItemText ( list_vehicles, Sweeper, vehicle_column, "Sweeper", false, false )
guiGridListSetItemText ( list_vehicles, Tahoma, vehicle_column, "Tahoma", false, false )
guiGridListSetItemText ( list_vehicles, Tampa, vehicle_column, "Tampa", false, false )
guiGridListSetItemText ( list_vehicles, Taxi, vehicle_column, "Taxi", false, false )
guiGridListSetItemText ( list_vehicles, Tornado, vehicle_column, "Tornado", false, false )
guiGridListSetItemText ( list_vehicles, Towtruck, vehicle_column, "Towtruck", false, false )
guiGridListSetItemText ( list_vehicles, Tractor, vehicle_column, "Tractor", false, false )
guiGridListSetItemText ( list_vehicles, Train, vehicle_column, "Train", false, false )
guiGridListSetItemText ( list_vehicles, Trashmaster, vehicle_column, "Trashmaster", false, false )
guiGridListSetItemText ( list_vehicles, Tropic, vehicle_column, "Tropic", false, false )
guiGridListSetItemText ( list_vehicles, Tug, vehicle_column, "Tug", false, false )
guiGridListSetItemText ( list_vehicles, turismo, vehicle_column, "Turismo", false, false )
guiGridListSetItemText ( list_vehicles, Uranus, vehicle_column, "Uranus", false, false )
guiGridListSetItemText ( list_vehicles, Utilityvan, vehicle_column, "Utility Van", false, false )
guiGridListSetItemText ( list_vehicles, Vincent, vehicle_column, "Vincent", false, false )
guiGridListSetItemText ( list_vehicles, Virgo, vehicle_column, "Virgo", false, false )
guiGridListSetItemText ( list_vehicles, Voodoo, vehicle_column, "Voodoo", false, false )
guiGridListSetItemText ( list_vehicles, vortex, vehicle_column, "Vortex", false, false )
guiGridListSetItemText ( list_vehicles, Walton, vehicle_column, "Walton", false, false )
guiGridListSetItemText ( list_vehicles, Washington, vehicle_column, "Washington", false, false )
guiGridListSetItemText ( list_vehicles, Wayfarer, vehicle_column, "Wayfarer", false, false )
guiGridListSetItemText ( list_vehicles, Willard, vehicle_column, "Willard", false, false )
guiGridListSetItemText ( list_vehicles, Windsor, vehicle_column, "Windsor", false, false )
guiGridListSetItemText ( list_vehicles, Yankee, vehicle_column, "Yankee", false, false )
guiGridListSetItemText ( list_vehicles, Yosemite, vehicle_column, "Yosemite", false, false )
guiGridListSetItemText ( list_vehicles, ZR350, vehicle_column, "ZR-350", false, false )
----------------------------------------------------------------------
guiGridListSetSortingEnabled ( list_vehicles, true )
guiGridListSetScrollBars ( list_vehicles, false, true )
destroy_button = guiCreateButton(421,503,189,86,"Destroy previous vehicle",false,Main_Window)
label_sorting = guiCreateLabel(362,51,277,21,"Click on the column 'Vehicles' to change sorting.",false,Main_Window)
Spawn_button = guiCreateButton(421,667,193,84,"Spawn!",false,Main_Window)
memo_Help = guiCreateMemo(405,184,222,81,"Welcome to my car spawning GUI! Select a car with your mouse and click Spawn to Spawn!",false,Main_Window)
guiMemoSetReadOnly(memo_Help,true)
credits = guiCreateLabel(377,875,251,35,"Created by: FabioGNR",false,Main_Window)
guiLabelSetColor(credits,255,255,255)
guiLabelSetVerticalAlign(credits,"top")
guiLabelSetHorizontalAlign(credits,"left",false)
addEventHandler ( "onClientGUIClick", Spawn_button, create_veh, false )
addEventHandler ( "onClientGUIClick", destroy_button, destroy_veh, false )
fix_button = guiCreateButton(425,291,187,43,"Fix vehicle",false,Main_Window)
category_button = guiCreateButton(428,454,187,44,"Sort/Categorize",false,Main_Window)
addEventHandler ( "onClientGUIClick", fix_button, fix_veh, false )
addEventHandler ( "onClientGUIClick", category_button, cat_list, false )
  end
 end
end

bindKey ( "F3", "down", displayGUI )

function fix_veh ()
	local vehicle = getPedOccupiedVehicle(g_Me)
	if vehicle then
		server.fixVehicle(vehicle)
	end
end

sorted = true

function cat_list ()
if sorted == true then 
sorted = false
removeEventHandler ( "onClientGUIClick", Spawn_button, create_veh )
addEventHandler ( "onClientGUIClick", Spawn_button, create_veh2 )
guiSetVisible ( list_vehicles, false )
guiSetVisible ( list_vehicles2, true )
else 
if sorted == false then
guiSetVisible ( list_vehicles2, false )
guiSetVisible ( list_vehicles, true )
sorted = true
removeEventHandler ( "onClientGUIClick", Spawn_button, create_veh2 )
addEventHandler ( "onClientGUIClick", Spawn_button, create_veh )
  end
 end
end


 
function create_veh2 ( playerSource, id )
local row, col = guiGridListGetSelectedItem( list_vehicles2 )
local name = guiGridListGetItemText( list_vehicles2, row, col )
--if name == "AT-400" and  then
if name == "Damaged Sadler" then
local id = 605
showCursor ( false )
guiSetVisible ( Main_Window, false )
ishidden = true
triggerServerEvent ( "spawn", getLocalPlayer(), id )
else
if name == "News Van" then
local id = 582
showCursor ( false )
guiSetVisible ( Main_Window, false )
ishidden = true
triggerServerEvent ( "spawn", getLocalPlayer(), id )
else
if name == "Damaged Glendale" then
local id = 604
showCursor ( false )
guiSetVisible ( Main_Window, false )
ishidden = true
triggerServerEvent ( "spawn", getLocalPlayer(), id )
else
local id = getVehicleModelFromName ( name )
showCursor ( false )
guiSetVisible ( Main_Window, false )
ishidden = true
triggerServerEvent ( "spawn", getLocalPlayer(), id )
      end
     end
    end
   end
  --end
  
  function create_veh ( playerSource, id )
local row, col = guiGridListGetSelectedItem( list_vehicles )
local name = guiGridListGetItemText( list_vehicles, row, col )
--if name == "AT-400" and  then
if name == "Damaged Sadler" then
local id = 605
showCursor ( false )
guiSetVisible ( Main_Window, false )
ishidden = true
triggerServerEvent ( "spawn", getLocalPlayer(), id )
else
if name == "News Van" then
local id = 582
showCursor ( false )
guiSetVisible ( Main_Window, false )
ishidden = true
triggerServerEvent ( "spawn", getLocalPlayer(), id )
else
if name == "Damaged Glendale" then
local id = 604
showCursor ( false )
guiSetVisible ( Main_Window, false )
ishidden = true
triggerServerEvent ( "spawn", getLocalPlayer(), id )
else
local id = getVehicleModelFromName ( name )
showCursor ( false )
guiSetVisible ( Main_Window, false )
ishidden = true
triggerServerEvent ( "spawn", getLocalPlayer(), id )
      end
     end
    end
   end

 function destroy_veh ()
 triggerServerEvent ( "destroy", getLocalPlayer() )
 end